name: Build stats & deploy Pages
on:
  schedule:
    - cron: "17 1 * * *"   # nightly 01:17 UTC
  workflow_dispatch:

# Needed for Pages deploy (no gh-pages branch push required)
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector (writes public/stats.json)
        env:
          # Prefer your PAT if present; otherwise fall back to the repo token
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          ORG: Avalanche-Team1-Africa
          WINDOW_DAYS: "30"
        run: python scripts/collect_stats.py

      - name: Build static site into public/
        run: |
          mkdir -p public
          cp -R site/* public/

      # Upload the built site as an artifact for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
