name: Collect Stats
on:
  schedule:
    - cron: "17 1 * * *"   # nightly 01:17 UTC
  workflow_dispatch:

permissions:
  contents: write    # needed to push to gh-pages

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run collector
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided by Actions; ok for public reads
          ORG: Avalanche-Team1-Africa
          WINDOW_DAYS: "30"
        run: python scripts/collect_stats.py

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages

    # (optional but nice) don’t run two copies at once
    concurrency:
      group: gh-stats
      cancel-in-progress: false
